---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../overlays/plus

images:
  - name: nginx-plus-ingress
    newName: ${repo}/nginx-plus-ingress
    newTag: 3.1.1

commonAnnotations: ${jsonencode(annotations)}
